export type Scene =
  | "entrance1"
  | "entrance2"
  | "corridor_main"
  | "straight"
  | "straight_left"
  | "straight_right"
  | "left_corridor"
  | "left_corridor1"
  | "left_class1"
  | "left_class2"
  | "right_corridor"
  | "right_corridor1"
  | "right_class1"
  | "right_class2"
  | "stairs_left_gf"
  | "stairs_right_gf"

  // FIRST FLOOR
  | "first_corridor_main"
  | "first_straight"
  | "first_straight_left"
  | "first_straight_right"
  | "first_left_corridor"
  | "first_left_corridor1"
  | "first_class1"
  | "first_class2"
  | "first_right_corridor"
  | "first_right_corridor1"
  | "first_right_class1"
  | "first_right_class2"
  | "stairs_left_ff"
  | "stairs_right_ff"

  // SECOND FLOOR
  | "second_corridor_main"
  | "second_straight"
  | "second_straight_left"
  | "second_straight_right"
  | "second_left_corridor"
  | "second_left_corridor1"
  | "second_class1"
  | "second_class2"
  | "second_right_corridor"
  | "second_right_corridor1"
  | "second_right_class1"
  | "second_right_class2"
  | "library"
  | "library2"
  | "library3"
  | "stairs_left_sf"
  | "stairs_right_sf"

  // THIRD FLOOR
  | "third_corridor_main"
  | "third_straight"
  | "third_straight_left"
  | "third_straight_right"
  | "third_left_corridor"
  | "third_left_corridor1"
  | "third_class1"
  | "third_class2"
  | "third_right_corridor"
  | "third_right_corridor1"
  | "third_right_class1"
  | "third_right_class2"
  | "auditorium";